2019-09-08 12:46:22,821 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\__init__.py:74]
2019-09-08 14:31:48,612 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:74]
2019-09-08 14:44:32,119 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:74]
2019-09-08 14:45:54,142 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:74]
2019-09-08 15:04:40,612 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:74]
2019-09-08 15:24:44,494 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:74]
2019-09-09 21:52:24,992 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:74]
2019-09-09 22:50:39,631 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:78]
2019-09-09 22:52:51,627 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:78]
2019-09-09 22:52:54,222 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:78]
2019-09-10 20:07:05,697 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:78]
2019-09-10 20:50:47,859 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:78]
2019-09-10 20:52:04,687 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:78]
2019-09-17 21:53:23,570 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:94]
2019-09-17 21:53:41,140 ERROR: Exception on / [POST] [in c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tomas\Desktop\Python\Websites\Microblog\app\main\routes.py", line 36, in index
    db.session.refresh()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
TypeError: refresh() missing 1 required positional argument: 'instance'
2019-09-17 21:58:52,211 ERROR: Exception on /index [POST] [in c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tomas\Desktop\Python\Websites\Microblog\app\main\routes.py", line 36, in index
    db.session.flush()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
TypeError: refresh() missing 1 required positional argument: 'instance'
2019-09-17 21:59:52,975 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Websites\Microblog\app\__init__.py:94]
